// Validates the vault: frontmatter parses, typed records match schema/*.json,
// wikilinks and embeds resolve, and nothing in content/ is tagged internal.
// Usage: node tools/validate.mjs   (exit 1 on any error)
import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import Ajv2020 from "ajv/dist/2020.js";

import { fileURLToPath } from "node:url";
const ROOT = fileURLToPath(new URL("..", import.meta.url));
const CONTENT = path.join(ROOT, "content");
const ajv = new Ajv2020({ allErrors: true, strict: false });
const schemas = {};
for (const f of fs.readdirSync(path.join(ROOT, "schema"))) {
  const type = f.replace(".schema.json", "");
  schemas[type] = ajv.compile(JSON.parse(fs.readFileSync(path.join(ROOT, "schema", f), "utf8")));
}

const walk = (dir) =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
    d.isDirectory() ? walk(path.join(dir, d.name)) : [path.join(dir, d.name)]);

const files = walk(CONTENT);
const pages = files.filter((f) => /\.(md|qmd)$/.test(f));
const rel = (f) => path.relative(CONTENT, f).split(path.sep).join("/");

// every way a wikilink may name a file: full path without extension, basename, or a title/alias
const targets = new Set();
const errors = [];
const parsed = [];
for (const f of pages) {
  const text = fs.readFileSync(f, "utf8");
  const m = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) { errors.push(`${rel(f)}: missing frontmatter`); continue; }
  let fm;
  try { fm = yaml.load(m[1]) ?? {}; } catch (e) { errors.push(`${rel(f)}: bad yaml: ${e.message}`); continue; }
  const noExt = rel(f).replace(/\.(md|qmd)$/, "");
  targets.add(noExt); targets.add(path.basename(noExt));
  if (noExt.endsWith("/index")) targets.add(noExt.slice(0, -6));
  if (fm.title) targets.add(String(fm.title));
  for (const a of fm.aliases ?? []) targets.add(String(a));
  parsed.push({ f, fm, body: text.slice(m[0].length) });
}
for (const f of files.filter((f) => !/\.(md|qmd)$/.test(f))) {
  targets.add(rel(f)); targets.add(rel(f).replace(/\.[^.]+$/, ""));
}

const draftTargets = new Set();
for (const { f, fm } of parsed) if (fm.draft === true) {
  const noExt = rel(f).replace(/\.(md|qmd)$/, "");
  draftTargets.add(noExt); draftTargets.add(path.basename(noExt)); if (fm.title) draftTargets.add(String(fm.title));
}
for (const { f, fm, body } of parsed) {
  const name = rel(f);
  if (!fm.title) errors.push(`${name}: no title`);
  for (const tag of fm.tags ?? []) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*(?:\/[a-z0-9]+(?:-[a-z0-9]+)*)?$/.test(tag))
      errors.push(`${name}: invalid tag ${tag}`);
  }
  if ((fm.tags ?? []).includes("internal") || (fm.tags ?? []).includes("private"))
    errors.push(`${name}: tagged internal/private but lives in content/ (public)`);
  if (fm.type && schemas[fm.type] && !schemas[fm.type](fm))
    for (const e of schemas[fm.type].errors) errors.push(`${name}: ${e.instancePath || "/"} ${e.message}`);
  const linkRe = /(!?)\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]/g;
  for (const [, , raw] of body.matchAll(linkRe)) {
    const t = raw.trim().replace(/\\$/, "").replace(/\.(md|qmd)$/, "");
    if (t.startsWith("tags/")) continue; // tag pages are generated by the site
    if (!targets.has(t) && !targets.has(path.basename(t))) errors.push(`${name}: unresolved link [[${raw}]]`);
    else if (fm.draft !== true && (draftTargets.has(t) || draftTargets.has(path.basename(t))))
      errors.push(`${name}: links to draft page [[${raw}]], which the site does not build (un-draft it or drop the link)`);
  }
  for (const [, raw] of body.matchAll(/!\[[^\]]*\]\(([^)]+)\)/g)) {
    if (/^https?:/.test(raw)) continue;
    const p = path.resolve(path.dirname(f), raw.split(/[ )]/)[0]);
    if (!fs.existsSync(p)) errors.push(`${name}: missing image ${raw}`);
  }
}

// Places are kept in one YAML file so rooms, occupants, and person profiles stay in sync.
const placesPath = path.join(CONTENT, "places", "places.yml");
if (fs.existsSync(placesPath)) {
  let data;
  try { data = yaml.load(fs.readFileSync(placesPath, "utf8")); }
  catch (e) { errors.push(`places/places.yml: bad yaml: ${e.message}`); }
  if (data && !schemas.places(data))
    for (const e of schemas.places.errors) errors.push(`places/places.yml: ${e.instancePath || "/"} ${e.message}`);
  if (data?.places) {
    const people = new Map(parsed.filter((p) => p.fm.type === "person").map((p) => [path.basename(p.f, path.extname(p.f)), p]));
    const places = new Map();
    for (const place of data.places) {
      if (places.has(place.id)) errors.push(`places/places.yml: duplicate id ${place.id}`);
      places.set(place.id, place);
    }
    for (const place of data.places) {
      if (place.building && !places.has(place.building)) errors.push(`places/places.yml: ${place.id} has unknown building ${place.building}`);
      for (const slug of place.occupants ?? []) {
        if (!people.has(slug)) errors.push(`places/places.yml: ${place.id} has unknown occupant ${slug}`);
        else if (!(people.get(slug).fm.places ?? []).includes(place.id))
          errors.push(`people/${slug}.md: missing places entry for ${place.id}`);
      }
    }
    for (const [slug, person] of people) for (const id of person.fm.places ?? []) {
      if (!places.has(id)) errors.push(`people/${slug}.md: unknown place ${id}`);
      else if (!(places.get(id).occupants ?? []).includes(slug)) errors.push(`places/places.yml: ${id} is missing occupant ${slug}`);
    }
  }
}

// equipment <-> setup cross references
const eq = new Set(parsed.filter((p) => p.fm.type === "equipment").map((p) => p.fm.id));
const setups = new Set(parsed.filter((p) => p.fm.type === "setup").map((p) => p.fm.id));
for (const { f, fm } of parsed) {
  if (fm.type === "equipment") for (const s of fm.setups ?? []) {
    const id = s.replace(/^\[\[setups\/|\]\]$/g, "");
    if (!setups.has(id)) errors.push(`${rel(f)}: unknown setup ${id}`);
  }
  if (fm.type === "setup") for (const e of fm.equipment ?? []) {
    const id = e.replace(/^\[\[equipment\/|\]\]$/g, "");
    if (!eq.has(id)) errors.push(`${rel(f)}: unknown equipment ${id}`);
  }
}

console.log(`${parsed.length} pages, ${eq.size} equipment records, ${setups.size} setups`);
if (errors.length) { console.error(errors.join("\n")); process.exit(1); }
console.log("vault ok");
